### ISSUE TITLE
Poggit-CI do not detect DiscordWebhookAPI as a virion

### ISSUE THREAD

**Issue by supercrafter333** [CortexPE/DiscordWebhookAPI#9]
Poggit do not detect the virion `DiscordWebhookAPI`. But pmforms will be detected from poggit.

My poggit.yml:
```yml
--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/supercrafter333/BetterBan
build-by-default: true
branches:
- master
- Dev
projects:
  BetterBan:
    path: ""
    icon: "icon.gif"
    libs:
      - src: CortexPE\DiscordWebhookAPI\DiscordWebhookAPI
        version: ^1.0
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^1.0.0
...
```
